name: Build

on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build and Lint
        run: |
          npm ci
          npm run lint

      - name: Recreating gh-pages
        run: |
          cd example
          npm i
          npm run build
          cd dist
          cp -r ../../.git .
          git config --local user.email "dipu.sudipta@gmail.com"
          git config --local user.name "dipu-bd"
          git branch -D gh-pages || true
          git checkout -b gh-pages
          git add --all
          git commit -m "[action] Update gh-pages"

      - name: Publish changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: example/dist
